GL_PROC(OpenGL, void, glActiveTexture, (GLenum a))
GL_PROC(OpenGL, void, glBeginQuery, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glBindBuffer, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glBindFramebuffer, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glBindRenderbuffer, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glBindTexture, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glBindVertexArray, (GLuint a))
GL_PROC(OpenGL, void, glBlendColor, (GLfloat a, GLfloat b, GLfloat c, GLfloat d))
GL_PROC(OpenGL, void, glBlendEquationSeparate, (GLenum a, GLenum b))
GL_PROC(OpenGL, void, glBlendFuncSeparate, (GLenum a, GLenum b, GLenum c, GLenum d))
GL_PROC(OpenGL, void, glBlitFramebuffer, (GLint a, GLint b, GLint c, GLint d, GLint e, GLint f, GLint g, GLint h, GLbitfield i, GLenum j))
GL_PROC(OpenGL, void, glBufferData, (GLenum a, GLsizeiptr b, const GLvoid *c, GLenum d))
GL_PROC(OpenGL, void, glBufferSubData, (GLenum a, GLintptr b, GLsizeiptr c, const GLvoid *d))
GL_PROC(OpenGL, void, glClear, (GLbitfield a))
GL_PROC(OpenGL, void, glClearColor, (GLclampf a, GLclampf b, GLclampf c, GLclampf d))
GL_PROC(OpenGL, void, glClearDepth, (GLdouble a))
GL_PROC(OpenGL, void, glClearDepthf, (GLfloat a))
GL_PROC(OpenGL, void, glClearStencil, (GLint s))
GL_PROC(OpenGL, void, glColorMask, (GLboolean a, GLboolean b, GLboolean c, GLboolean d))
GL_PROC(OpenGL, void, glColorMaski, (GLuint a, GLboolean b, GLboolean c, GLboolean d, GLboolean e))
GL_PROC(OpenGL, void, glDebugMessageCallback, (DEBUGPROC a, const GLvoid *b))
GL_PROC(OpenGL, void, glDebugMessageControl, (GLenum a, GLenum b, GLenum c, GLsizei d, const GLuint *e, GLboolean f))
GL_PROC(OpenGL, void, glDeleteBuffers, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDeleteFramebuffers, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDeleteQueries, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDeleteRenderbuffers, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDeleteTextures, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDeleteVertexArrays, (GLsizei a, const GLuint *b))
GL_PROC(OpenGL, void, glDepthFunc, (GLenum a))
GL_PROC(OpenGL, void, glDepthMask, (GLboolean a))
GL_PROC(OpenGL, void, glDepthRange, (GLdouble a, GLdouble b))
GL_PROC(OpenGL, void, glDepthRangef, (GLfloat a, GLfloat b))
GL_PROC(OpenGL, void, glDisable, (GLenum a))
GL_PROC(OpenGL, void, glDisableVertexAttribArray, (GLint a))
GL_PROC(OpenGL, void, glDrawArrays, (GLenum a, GLint b, GLsizei c))
GL_PROC(OpenGL, void, glDrawBuffers, (GLsizei a, const GLenum *b))
GL_PROC(OpenGL, void, glDrawElements, (GLenum a, GLsizei b, GLenum c, const GLvoid *d))
GL_PROC(OpenGL, void, glDrawElementsInstanced, (GLenum a, GLsizei b, GLenum c, const GLvoid *d, GLsizei e))
GL_PROC(OpenGL, void, glDrawElementsInstancedBaseVertex, (GLenum a, GLsizei b, GLenum c, const GLvoid *d, GLsizei e, GLint f))
GL_PROC(OpenGL, void, glDrawRangeElements, (GLenum a, GLuint b, GLuint c, GLsizei d, GLenum e, const GLvoid *f))
GL_PROC(OpenGL, void, glDrawRangeElementsBaseVertex, (GLenum a, GLuint b, GLuint c, GLsizei d, GLenum e, const GLvoid *f, GLint g))
GL_PROC(OpenGL, void, glEnable, (GLenum a))
GL_PROC(OpenGL, void, glEnableVertexAttribArray, (GLint a))
GL_PROC(OpenGL, void, glEndQuery, (GLenum a))
GL_PROC(OpenGL, void, glFramebufferRenderbuffer, (GLenum a, GLenum b, GLenum c, GLuint d))
GL_PROC(OpenGL, void, glFramebufferTexture2D, (GLenum a, GLenum b, GLenum c, GLuint d, GLint e))
GL_PROC(OpenGL, void, glFrontFace, (GLenum a))
GL_PROC(OpenGL, void, glGenBuffers, (GLint a, GLuint *b))
GL_PROC(OpenGL, void, glGenerateMipmap, (GLenum a))
GL_PROC(OpenGL, void, glGenFramebuffers, (GLsizei a, GLuint *b))
GL_PROC(OpenGL, void, glGenRenderbuffers, (GLsizei a, GLuint *b))
GL_PROC(OpenGL, void, glGenTextures, (GLsizei a, GLuint *b))
GL_PROC(OpenGL, void, glGenQueries, (GLsizei a, GLuint *b))
GL_PROC(OpenGL, void, glGenVertexArrays, (GLsizei a, GLuint *b))
GL_PROC(OpenGL, GLenum, glGetIntegerv, (GLenum a, GLint *b))
GL_PROC(OpenGL, void, glGetQueryObjectuiv, (GLuint a, GLenum b, GLuint *c))
GL_PROC(OpenGL, const GLubyte*, glGetString, (GLenum a))
GL_PROC(OpenGL, const GLubyte*, glGetStringi, (GLenum a, GLuint b))
GL_PROC(OpenGL, void, glGetTexImage, (GLenum a, GLint b, GLenum c, GLenum d, GLvoid *e))
GL_PROC(OpenGL, void, glInvalidateFramebuffer, (GLenum a, GLsizei b, const GLenum *c))
GL_PROC(OpenGL, void, glPixelStorei, (GLenum a, GLint b))
GL_PROC(OpenGL, void, glPolygonMode, (GLenum a, GLenum b))
GL_PROC(OpenGL, void, glPolygonOffset, (GLfloat a, GLfloat b))
GL_PROC(OpenGL, void, glReadPixels, (GLint a, GLint b, GLsizei c, GLsizei d, GLenum e, GLenum f, const GLvoid *g))
GL_PROC(OpenGL, void, glRenderbufferStorage, (GLenum a, GLenum b, GLsizei c, GLsizei d))
GL_PROC(OpenGL, void, glRenderbufferStorageMultisample, (GLenum a, GLsizei b, GLenum c, GLsizei d, GLsizei e))
GL_PROC(OpenGL, void, glSampleMaski, (GLuint a, GLuint b))
GL_PROC(OpenGL, void, glScissor, (GLint a, GLint b, GLint c, GLint d))
GL_PROC(OpenGL, void, glStencilFunc, (GLenum a, GLint b, GLint c))
GL_PROC(OpenGL, void, glStencilOp, (GLenum a, GLenum b, GLenum c))
GL_PROC(OpenGL, void, glStencilOpSeparate, (GLenum a, GLenum b, GLenum c, GLenum d))
GL_PROC(OpenGL, void, glStencilMask, (GLint a))
GL_PROC(OpenGL, void, glCompressedTexImage2D, (GLenum a, GLint b, GLenum c, GLsizei d, GLsizei e, GLint f, GLsizei g, const GLvoid *h))
GL_PROC(OpenGL, void, glCompressedTexSubImage2D, (GLenum a, GLint b, GLint c, GLint d, GLsizei e, GLsizei f, GLenum g, GLsizei h, const GLvoid *i))
GL_PROC(OpenGL, void, glTexEnvi, (GLenum a, GLenum b, GLint c))
GL_PROC(OpenGL, void, glTexImage2D, (GLenum a, GLint b, GLint c, GLsizei d, GLsizei e, GLint f, GLenum g, GLenum h, const GLvoid *i))
GL_PROC(OpenGL, void, glTexImage3D, (GLenum a, GLint b, GLint c, GLsizei d, GLsizei e, GLsizei f, GLint g, GLenum h, GLenum i, const GLvoid *j))
GL_PROC(OpenGL, void, glTexParameterf, (GLenum a, GLenum b, GLfloat c))
GL_PROC(OpenGL, void, glTexParameteri, (GLenum a, GLenum b, GLint c))
GL_PROC(OpenGL, void, glTexSubImage2D, (GLenum a, GLint b, GLint c, GLint d, GLsizei e, GLsizei f, GLenum g, GLenum h, const GLvoid *i))
GL_PROC(OpenGL, void, glTexSubImage3D, (GLenum a, GLint b, GLint c, GLint d, GLint e, GLsizei f, GLsizei g, GLsizei h, GLenum i, GLenum j, const GLvoid *k))
GL_PROC(OpenGL, void, glVertexAttribDivisor, (GLuint a, GLuint b))
GL_PROC(OpenGL, void, glVertexAttribPointer, (GLuint a, GLint b, GLenum c, GLboolean d, GLsizei e, const GLvoid *f))
GL_PROC(OpenGL, void, glViewport, (GLint a, GLint b, GLsizei c, GLsizei d))
#ifdef STRINGDEBUG
GL_PROC(OpenGL, void, glStringMarkerGREMEDY, (GLsizei a, const GLchar *b))
#endif
