GL_PROC(BaseGL, void, glActiveTexture, (GLenum a))
GL_PROC(NonES3, void, glBeginQuery, (GLenum a, GLuint b))
GL_PROC(BaseGL, void, glBindBuffer, (GLenum a, GLuint b))
GL_PROC(FBO, void, glBindFramebuffer, (GLenum a, GLuint b))
GL_PROC(FBO, void, glBindRenderbuffer, (GLenum a, GLuint b))
GL_PROC(BaseGL, void, glBindTexture, (GLenum a, GLuint b))
GL_PROC(CoreGL, void, glBindVertexArray, (GLuint a))
GL_PROC(BaseGL, void, glBlendColor, (GLfloat a, GLfloat b, GLfloat c, GLfloat d))
GL_PROC(BaseGL, void, glBlendEquationSeparate, (GLenum a, GLenum b))
GL_PROC(BaseGL, void, glBlendFuncSeparate, (GLenum a, GLenum b, GLenum c, GLenum d))
GL_PROC(MiscGL, void, glBlitFramebuffer, (GLint a, GLint b, GLint c, GLint d, GLint e, GLint f, GLint g, GLint h, GLbitfield i, GLenum j))
GL_PROC(BaseGL, void, glBufferData, (GLenum a, GLsizeiptr b, const GLvoid *c, GLenum d))
GL_PROC(BaseGL, void, glBufferSubData, (GLenum a, GLintptr b, GLsizeiptr c, const GLvoid *d))
GL_PROC(BaseGL, void, glClear, (GLbitfield a))
GL_PROC(BaseGL, void, glClearColor, (GLclampf a, GLclampf b, GLclampf c, GLclampf d))
GL_PROC(MiscGL, void, glClearDepth, (GLdouble a))
GL_PROC(MiscGL, void, glClearDepthf, (GLfloat a))
GL_PROC(BaseGL, void, glClearStencil, (GLint s))
GL_PROC(BaseGL, void, glColorMask, (GLboolean a, GLboolean b, GLboolean c, GLboolean d))
GL_PROC(MiscGL, void, glColorMaski, (GLuint a, GLboolean b, GLboolean c, GLboolean d, GLboolean e))
GL_PROC(BaseGL, void, glDeleteBuffers, (GLsizei a, const GLuint *b))
GL_PROC(FBO, void, glDeleteFramebuffers, (GLsizei a, const GLuint *b))
GL_PROC(NonES3, void, glDeleteQueries, (GLsizei a, const GLuint *b))
GL_PROC(FBO, void, glDeleteRenderbuffers, (GLsizei a, const GLuint *b))
GL_PROC(BaseGL, void, glDeleteTextures, (GLsizei a, const GLuint *b))
GL_PROC(CoreGL, void, glDeleteVertexArrays, (GLsizei a, const GLuint *b))
GL_PROC(BaseGL, void, glDepthFunc, (GLenum a))
GL_PROC(BaseGL, void, glDepthMask, (GLboolean a))
GL_PROC(MiscGL, void, glDepthRange, (GLdouble a, GLdouble b))
GL_PROC(MiscGL, void, glDepthRangef, (GLfloat a, GLfloat b))
GL_PROC(BaseGL, void, glDisable, (GLenum a))
GL_PROC(BaseGL, void, glDisableVertexAttribArray, (GLint a))
GL_PROC(BaseGL, void, glDrawArrays, (GLenum a, GLint b, GLsizei c))
GL_PROC(BaseGL, void, glDrawBuffers, (GLsizei a, const GLenum *b))
GL_PROC(MiscGL, void, glDrawElements, (GLenum a, GLsizei b, GLenum c, const GLvoid *d))
GL_PROC(MiscGL, void, glDrawElementsInstanced, (GLenum a, GLsizei b, GLenum c, const GLvoid *d, GLsizei e))
GL_PROC(MiscGL, void, glDrawElementsInstancedBaseVertex, (GLenum a, GLsizei b, GLenum c, const GLvoid *d, GLsizei e, GLint f))
GL_PROC(MiscGL, void, glDrawRangeElements, (GLenum a, GLuint b, GLuint c, GLsizei d, GLenum e, const GLvoid *f))
GL_PROC(MiscGL, void, glDrawRangeElementsBaseVertex, (GLenum a, GLuint b, GLuint c, GLsizei d, GLenum e, const GLvoid *f, GLint g))
GL_PROC(BaseGL, void, glEnable, (GLenum a))
GL_PROC(BaseGL, void, glEnableVertexAttribArray, (GLint a))
GL_PROC(NonES3, void, glEndQuery, (GLenum a))
GL_PROC(FBO, void, glFramebufferRenderbuffer, (GLenum a, GLenum b, GLenum c, GLuint d))
GL_PROC(FBO, void, glFramebufferTexture2D, (GLenum a, GLenum b, GLenum c, GLuint d, GLint e))
GL_PROC(BaseGL, void, glFrontFace, (GLenum a))
GL_PROC(BaseGL, void, glGenBuffers, (GLint a, GLuint *b))
GL_PROC(FBO, void, glGenerateMipmap, (GLenum a))
GL_PROC(FBO, void, glGenFramebuffers, (GLsizei a, GLuint *b))
GL_PROC(FBO, void, glGenRenderbuffers, (GLsizei a, GLuint *b))
GL_PROC(BaseGL, void, glGenTextures, (GLsizei a, GLuint *b))
GL_PROC(NonES3, void, glGenQueries, (GLsizei a, GLuint *b))
GL_PROC(CoreGL, void, glGenVertexArrays, (GLsizei a, GLuint *b))
GL_PROC(OptES3, void, glGetBufferSubData, (GLenum a, GLintptr b, GLsizeiptr c, GLvoid *d))
GL_PROC(BaseGL, GLenum, glGetIntegerv, (GLenum a, GLint *b))
GL_PROC(NonES3, void, glGetQueryObjectuiv, (GLuint a, GLenum b, GLuint *c))
GL_PROC(MiscGL, const GLubyte*, glGetString, (GLenum a))
GL_PROC(CoreGL, const GLubyte*, glGetStringi, (GLenum a, GLuint b))
GL_PROC(OptES3, void, glGetTexImage, (GLenum a, GLint b, GLenum c, GLenum d, GLvoid *e))
GL_PROC(MiscGL, void, glInvalidateFramebuffer, (GLenum a, GLsizei b, const GLenum *c))
GL_PROC(BaseGL, void, glPixelStorei, (GLenum a, GLint b))
GL_PROC(OptES3, void, glPolygonMode, (GLenum a, GLenum b))
GL_PROC(BaseGL, void, glPolygonOffset, (GLfloat a, GLfloat b))
GL_PROC(BaseGL, void, glReadPixels, (GLint a, GLint b, GLsizei c, GLsizei d, GLenum e, GLenum f, const GLvoid *g))
GL_PROC(FBO, void, glRenderbufferStorage, (GLenum a, GLenum b, GLsizei c, GLsizei d))
GL_PROC(MiscGL, void, glRenderbufferStorageMultisample, (GLenum a, GLsizei b, GLenum c, GLsizei d, GLsizei e))
GL_PROC(MiscGL, void, glSampleMaski, (GLuint a, GLuint b))
GL_PROC(BaseGL, void, glScissor, (GLint a, GLint b, GLint c, GLint d))
GL_PROC(BaseGL, void, glStencilFunc, (GLenum a, GLint b, GLint c))
GL_PROC(BaseGL, void, glStencilFuncSeparate, (GLenum a, GLenum b, GLenum c, GLenum d))
GL_PROC(BaseGL, void, glStencilOp, (GLenum a, GLenum b, GLenum c))
GL_PROC(BaseGL, void, glStencilOpSeparate, (GLenum a, GLenum b, GLenum c, GLenum d))
GL_PROC(BaseGL, void, glStencilMask, (GLint a))
GL_PROC(BaseGL, void, glCompressedTexImage2D, (GLenum a, GLint b, GLenum c, GLsizei d, GLsizei e, GLint f, GLsizei g, const GLvoid *h))
GL_PROC(BaseGL, void, glCompressedTexSubImage2D, (GLenum a, GLint b, GLint c, GLint d, GLsizei e, GLsizei f, GLenum g, GLsizei h, const GLvoid *i))
GL_PROC(OptES3, void, glTexEnvi, (GLenum a, GLenum b, GLint c))
GL_PROC(BaseGL, void, glTexImage2D, (GLenum a, GLint b, GLint c, GLsizei d, GLsizei e, GLint f, GLenum g, GLenum h, const GLvoid *i))
GL_PROC(NonES3, void, glTexImage3D, (GLenum a, GLint b, GLint c, GLsizei d, GLsizei e, GLsizei f, GLint g, GLenum h, GLenum i, const GLvoid *j))
GL_PROC(BaseGL, void, glTexParameterf, (GLenum a, GLenum b, GLfloat c))
GL_PROC(BaseGL, void, glTexParameteri, (GLenum a, GLenum b, GLint c))
GL_PROC(BaseGL, void, glTexSubImage2D, (GLenum a, GLint b, GLint c, GLint d, GLsizei e, GLsizei f, GLenum g, GLenum h, const GLvoid *i))
GL_PROC(NonES3, void, glTexSubImage3D, (GLenum a, GLint b, GLint c, GLint d, GLint e, GLsizei f, GLsizei g, GLsizei h, GLenum i, GLenum j, const GLvoid *k))
GL_PROC(MiscGL, void, glVertexAttribDivisor, (GLuint a, GLuint b))
GL_PROC(BaseGL, void, glVertexAttribPointer, (GLuint a, GLint b, GLenum c, GLboolean d, GLsizei e, const GLvoid *f))
GL_PROC(BaseGL, void, glViewport, (GLint a, GLint b, GLsizei c, GLsizei d))
#ifdef DEBUG
GL_PROC(MiscGL, void, glDebugMessageCallback, (DEBUGPROC a, const GLvoid *b))
GL_PROC(MiscGL, void, glDebugMessageControl, (GLenum a, GLenum b, GLenum c, GLsizei d, const GLuint *e, GLboolean f))
GL_PROC(MiscGL, void, glStringMarkerGREMEDY, (GLsizei a, const GLchar *b))
#endif
